# Generated by Django 4.0.5 on 2022-07-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='color',
            field=models.CharField(default='None', max_length=120, verbose_name='Color'),
        ),
    ]
