# Generated by Django 4.0.5 on 2022-07-15 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopcategory_active_shopitem_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopmodel',
            name='category',
        ),
        migrations.CreateModel(
            name='ShopCategoryCrossModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopcategory')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shopmodel')),
            ],
        ),
    ]
