# Generated by Django 4.0.5 on 2022-07-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shopmodel_category_shopcategorycrossmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopmodel',
            name='categories',
            field=models.ManyToManyField(to='shop.shopcategory'),
        ),
        migrations.DeleteModel(
            name='ShopCategoryCrossModel',
        ),
    ]
